<?php

/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Kamlesh\MultipleWishlist\ViewModel\MultipleWishlist $viewModel
 */
$viewModel = $block->getViewModel();
?>
<?php if ($viewModel->isCustomerLoggedIn() && $viewModel->canShowModal()): ?>
    <div class="multiplewishlist-modal" data-mage-init='{"multipleWishlistModal": {}}'
         data-bind="scope: 'multiple_wishlists'" data-item="multiple_wishlists">
    <!-- Styles moved to view/frontend/web/css/modal.css -->
        <form id="multiple-wishlist-form" action="#" method="post">
            <p class="multiple-wishlist-note"><?= __('If no wishlist is selected, item will be added to the Default Wishlist.'); ?></p>
            <!-- ko ifnot: hasWishlists() -->
                <p><?= __('You don\'t have created wishlists.'); ?></p>
            <!-- /ko -->

            <!-- ko template: getTemplate() --><!-- /ko -->
        </form>
    </div>

    <script type="text/x-magento-init">
        {
            "[data-item='multiple_wishlists']": {
                "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout(); ?>
            }
        }
    </script>
<?php endif; ?>
